import {
  clientHints,
  getClientHintCookieValue,
  themeCookieName,
} from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { ReadonlyRequestCookies } from "next/dist/server/web/spec-extension/adapters/request-cookies";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { ClientHintCheck } from "@/lib/client-hint";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Returns the cookie value set by server or use client-hint of the user
export function getTheme(cookies: ReadonlyRequestCookies) {
  const themeValue = cookies.get(themeCookieName)?.value;

  if (themeValue === "light" || themeValue === "dark") return themeValue;

  return getClientHintCookieValue(clientHints[themeCookieName], cookies);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStorage = cookies();
  const theme = getTheme(cookieStorage);

  return (
    <html lang="en" className={theme}>
      <head>
        <ClientHintCheck />
      </head>
      <body className={inter.className}>
        {theme === "light" && <div>Oh boy !! I see light theme</div>}
        {theme === "dark" && <div>Oh boy !! I see dark theme</div>}
        {children}
      </body>
    </html>
  );
}
